name = "svelte-swsr"
account_id = 'e20ebc96b0121ea21bf59ea0a95e7997'
type = "javascript"
main = "./.cloudflare/index.js"
compatibility_date = "2022-06-09"

kv_namespaces = [
    { binding = "KV_SVELTE_SWSR", id = "a1b554acb593408caf051d3b829a5de2" }
]

[build]
command = "npm run build"

[site]
bucket = "./.cloudflare/assets"